### PR TITLE
Update Runtime(s) to 23.08

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by Erick555** [comment]
You may reconsider replacing bundled ffmpeg with ffmpeg-full extension again, the 23.08 ffmpeg-full is much more full than before.

**Comment by maxrd2** [comment]
Is it possible to freeze/remove subtitlecomposer from flathub for the time being?  

I really don't have time to troubleshoot, test and support another distribution/platform with all of its quirks, rules and requirements.

I suppose down the road there will be someone that has time and will to do this properly and they could pick up from here.

**Comment by Erick555** [comment]
I think kde flatpaks are maintained collectively by kde team. This app seems to work just fine, _freezing_ it doesn't make much sense then.

**Comment by Justinzobel** [comment]
Yes, we (the KDE Flathub Team) are happy to continue maintaining this.

**Comment by maxrd2** [comment]
Thank you all for your work.

I apologize if my previous comment came off as rude, it was not my intention, I just meant that some fixes *might* need changes in subtitlecomposer code.
Last time I've tried the flatpak version there were issues with reading/writing files on the filesystem. The flag `--filesystem=host ` was not enough and file dialogs kept passing temp path even with that flag is set.
The ffmpeg change was done due to some media codecs not playing properly. IIRC codec in question was H.264 with some less common encoding parameters.

**Comment by Justinzobel** [comment]
> Thank you all for your work.
> 
> I apologize if my previous comment came off as rude, it was not my intention, I just meant that some fixes _might_ need changes in subtitlecomposer code. Last time I've tried the flatpak version there were issues with reading/writing files on the filesystem. The flag `--filesystem=host ` was not enough and file dialogs kept passing temp path even with that flag is set. The ffmpeg change was done due to some media codecs not playing properly. IIRC codec in question was H.264 with some less common encoding parameters.

Not a problem at all. Your previous comment was fine. I've been told the ffmpeg-full platform has come a long way lately.

**Comment by Erick555** [comment]
Looks good to me.

> The flag --filesystem=host was not enough and file dialogs kept passing temp path even with that flag is set.

This is indeed interesting behavior and I don't know how that is even possible. It's not a deal breaker though.

**Comment by Erick555** [comment]
@Justinzobel @travier can someone merge this?

**Pull request merged**
